apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sArgoCDPolicy
spec:
  crd:
    spec:
      names:
        kind: k8sArgoCDPolicy
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8simagepolicy
        violation[{"msg": msg}] {
            input.review.kind.kind == "Application"
            input.review.object.spec.project == "default"
            input.review.object.spec.destination.namespace == "ecommerce"
            msg := "The project 'default' is not authorized to deploy in 'ecommerce'."
        }

        violation[{"msg": msg}] {
            input.review.kind.kind == "Application"
            some s
            source_url := input.review.object.spec.sources[s].repoURL
            
            not input.parameters.approvedUrls[_] == source_url
            
            msg := sprintf("The URL of the repo '%q' is not on the list of approved sources.", [source_url])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sArgoCDPolicy
metadata:
  name: argocd-approved-repos
spec:
  enforcementAction : dryrun
  match:
    kinds:
      - apiGroups: ["argoproj.io"]
        kinds: ["Application"]
    namespace:
      - ecommerce
  parameters:
    approvedUrls:
      https://github.com/Titou-Onee/CloudDevOps_ecommerce.git