apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yml
- templates/access-roles-policy.yml
- templates/argocd-applications-policy.yml
- templates/image-security-policy.yml
- templates/namespace-label-policy.yml
- templates/pod-security-policy.yml
- templates/ressource-security-policy.yml

- constaints/access-roles-constaints.yml
- constaints/argocd-applications-constaints.yml
- constaints/image-security-constaints.yml
- constaints/namespace-label-constaints.yml
- constaints/pod-security-constaints.yml
- constaints/ressource-security-constaints.yml 

commonLabels:
  app.kubernetes.io/managed-by: gatekeeper
  app.kubernetes.io/name: gatekeeper-policy

