apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yml
- templates/access-roles-policy.yml
- templates/argocd-applications-policy.yml
- templates/image-security-policy.yml
- templates/namespace-label-policy.yml
- templates/pod-security-policy.yml
- templates/ressource-security-policy.yml

- constraints/access-roles-constraint.yml
- constraints/argocd-applications-constraint.yml
- constraints/image-security-constraint.yml
- constraints/namespace-label-constraint.yml
- constraints/pod-security-constraint.yml
- constraints/ressource-security-constraint.yml 

commonLabels:
  app.kubernetes.io/managed-by: gatekeeper
  app.kubernetes.io/name: gatekeeper-policy

