apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yml
- templates/ 
- constaints/ 

commonLabels:
  app.kubernetes.io/managed-by: gatekeeper
  app.kubernetes.io/name: gatekeeper-policy

