# template for use of default project / unapproved source
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sargocdpolicy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  crd:
    spec:
      names:
        kind: k8sArgocdPolicy
      validation:
        openAPIV3Schema:
          type: object
          properties:
            approvedUrls:
              type: array
              description: "List of authorized URLs."
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sargocdpolicy
        violation[{"msg": msg}] {
            input.review.kind.kind == "Application"
            input.review.object.spec.project == "default"
            msg := "The project 'default' is not authorized to deploy in 'ecommerce'."
        }

        violation[{"msg": msg}] {
          input.review.kind.kind == "Application"
          some s
          source_url := input.review.object.spec.sources[s].repoURL
          not source_url_in_list(source_url, input.parameters.approvedUrls)
          msg := sprintf("The URL of the repo '%q' is not on the list of approved sources.", [source_url])
        }

        source_url_in_list(url, list) {
          some i
          list[i] == url
        }

