apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: ecommerce
data:
  01-init.sql: |
    ALTER ROLE django_user CREATEDB CREATEROLE;
    GRANT ALL PRIVILEGES ON DATABASE ecommerce_db TO django_user;
