apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: ecommerce
data:
  01-init-user.sh: |
    #!/bin/bash
    set -e

    
    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL

        GRANT ALL PRIVILEGES ON DATABASE postgres TO admin-user;
        
        GRANT ALL ON SCHEMA public TO admin-user;
        GRANT CREATE ON SCHEMA public TO admin-user;
      
        
        ALTER USER admin-user CREATEDB;
    EOSQL
    
    echo "Utilisateur créé et droits attribués avec succès!"


#       GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_USERNAME;
#        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRESQL_USERNAME;
        
#       ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $POSTGRESQL_USERNAME;
#       ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $POSTGRESQL_USERNAME;
#       ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $POSTGRESQL_USERNAME;