apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: ecommerce
data:
  01-init-user.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "db" <<-EOSQL
        ALTER SCHEMA public OWNER TO "admin-user";
        GRANT ALL PRIVILEGES ON DATABASE db TO "admin-user";
        GRANT ALL PRIVILEGES ON SCHEMA public TO "admin-user";
        GRANT CREATE ON SCHEMA public TO "admin-user";
    EOSQL



#       GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_USERNAME;
#        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRESQL_USERNAME;
        
#       ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $POSTGRESQL_USERNAME;
#       ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $POSTGRESQL_USERNAME;
#       ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $POSTGRESQL_USERNAME;