apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: ecommerce
data:
  01-init-user.sql: |
        GRANT USAGE ON SCHEMA public TO "admin-user";
        GRANT CREATE ON SCHEMA public TO "admin-user";

        ALTER SCHEMA public OWNER TO "admin-user";
        
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "admin-user";
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "admin-user";
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "admin-user";