apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      serviceAccountName: ecommerce-app-sa 
      securityContext:

      initContainers:
        - name: postgres-migration
          image: titouonee/clouddevops_ecommerce
          command: ['python3', 'manage.py', 'migrate']
          envFrom:
            - secretRef:
                name: ecommerce-secret
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
            allowPrivilegeEscalation: false
      containers:
      - name: ecommerce-app
        image: titouonee/clouddevops_ecommerce
        command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 3000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        ports:
        - containerPort: 8000
          name: http
        envFrom:
          - secretRef:
              name: ecommerce-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi" 
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  selector:
    app: ecommerce-app
  ports:
  - name: ecommerce-port
    protocol: TCP 
    port: 80
    targetPort: 8000
  type: ClusterIP