apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      serviceAccountName: ecommerce-app-sa 
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      initContainers:
        - name: postgres-migration
          image: titouonee/clouddevops_ecommerce
          command: ['python3', 'manage.py', 'migrate']
          envFrom:
            - secretRef:
                name: ecommerce-secret
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - NET_RAW
                - ALL 
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi" 
              cpu: "500m"
      containers:
        - name: ecommerce-app
          image: titouonee/clouddevops_ecommerce
          command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: 
            capabilities:
                drop:
                  - ALL 
                  - NET_RAW
          ports:
          - containerPort: 8000
            name: http
          envFrom:
            - secretRef:
                name: ecommerce-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi" 
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  selector:
    app: ecommerce-app
  ports:
  - name: ecommerce-port
    protocol: TCP 
    port: 80
    targetPort: 8000
  type: ClusterIP