# role for the ecommerce app
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecommerce-app-role
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: ecommerce-app
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"] 

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecommerce-app-rolebinding
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: ecommerce-app
subjects:
  - kind: ServiceAccount
    name: ecommerce-app-sa
    namespace: ecommerce
roleRef:
  kind: Role
  name: ecommerce-app-role
  apiGroup: rbac.authorization.k8s.io