apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization




resources:
- namespace.yml
- configmap.yml
- ressource_quota.yml
- secrets.yml
- service_accounts.yml
- ecommerce_roles.yml
- network_policy.yml
- postgress_pvc.yml
- postgres_deployment.yml
- ecommerce_deployment.yml
- ingress.yml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/name: ecommerce-app

images:
- name: titouonee/clouddevops_ecommerce
  newTag: e033a09e57df757625d88e64cf7c1008ab51700f
