apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization





resources:
- namespace.yml
- sealed-secrets.yml
- service_accounts.yml
- ecommerce_roles.yml
- network_policy.yml
- postgress_pvc.yml
- postgres_deployment.yml
- ecommerce_deployment.yml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/name: ecommerce-app

images:
- name: titouonee/clouddevops_ecommerce
  newTag: 6115eb572e30f7c4ea8b0c4a4247d41ed1bbdebb
