apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization





resources:
- namespace.yml
- sealed-secrets.yml
- service_accounts.yml
- ecommerce_roles.yml
- network_policy.yml
- postgress_pvc.yml
- postgres_deployment.yml
- ecommerce_deployment.yml
- ingress.yml
- not-secure-private-key.yml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/name: ecommerce-app

images:
- name: titouonee/clouddevops_ecommerce
  newTag: b210d57596a70bc2475abf64bd630461f9f5465c
