# kustomize for application deployment and image update
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization





resources:
- sealed-secrets.yml
- service_accounts.yml
- ingress.yml
- ecommerce_roles.yml
- network_policy.yml
- postgress_pvc.yml
- postgres_deployment.yml
- ecommerce_deployment.yml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/name: ecommerce-app

images:
- name: titouonee/clouddevops_ecommerce
  newTag: b16b38ce6ee07c3bb5ed09e817c1ac381d1887e0
