# Namespace creation, quota and limitRange
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    app.kubernetes.io/name: ecommerce
    app.kubernetes.io/instance: ecommerce-prod
    app.kubernetes.io/managed-by: argocd
  annotations: 
    kubernetes.io/enforce-policy: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecommerce-quota
  namespace: ecommerce
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    requests.cpu: "2"
    requests.memory: 4Gi

    count/pods: "20"
    count/services: "10"
    count/replicationcontrollers: "5"
    count/deployments.apps: "5"
    
    requests.storage: 20Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ecommerce-limit-range
  namespace: ecommerce
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      max:
        cpu: 1000m
        memory: 2Gi
      min:
        cpu: 50m
        memory: 128Mi

    - type: Pod
      max:
        cpu: 4
        memory: 4Gi
      min:
        cpu: 100m
        memory: 128Mi

