# Unsealed secret (not used in the kustomize)
# For learning purpose, this file is the secret file before the seal
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRESQL_USERNAME: admin-user
  POSTGRESQL_PASSWORD: unsecure-admin-password
  POSTGRESQL_DATABASE: db
  POSTGRESQL_POSTGRES_PASSWORD: django-pass