apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecommerce-resource-quota
  namespace: ecommerce
spec:
  hard:
    requests.cpu: "4"         # Max 4 CPU cores de requests
    requests.memory: 8Gi      # Max 8 GiB de requests
    limits.cpu: "8"           # Max 8 CPU cores de limits
    limits.memory: 16Gi       # Max 16 GiB de limits
    count/pods: 50                  # Max 50 Pods
    count/services: 10              # Max 10 Services
    count/deployments.apps: "5"     # Max 5 Deployments
