# Worflow for terraform checks
name: Terraform
on:
  push:
    branches:
        - master
    paths:
        - '**.tf'
        - '**.tfvars'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform/infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.7

      - name: Terraform init
        run: terraform init
        env:
           TF_VAR_aws_region: eu-west-3

      - name: Terraform format
        run: terraform fmt --check -recursive
        continue-on-error: true

      - name: Terraform validation
        run: terraform validate
        continue-on-error: true

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with: 
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost breakdown
        run: |
          infracost breakdown --path=. \
                              --format=table \
                              --show-skipped
      
      - name: Generate Infracost JSON output
        run: |
          infracost breakdown --path=. \
                              --format=table \
                              --out-file=infracost-report.txt

      - name: TSetup TFlint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.60.0

      - name: Run TFlint
        run: tflint --recursive
        continue-on-error: true

      - name: TFsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          additional_args: >
            --format cli
            --concise-output
            --out tfsec-report.txt
        continue-on-error: true

      - name: Checkov
        uses: bridgecrewio/checkov-action@v3
        with:
          framework: terraform
          output_format: cli
          output_file_path: console,checkov-report.txt
        continue-on-error: true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: terraform-security-report
          path: |
            checkov-report.txt
            tfsec-report.txt
            infracost-report.txt
          retention-days: 1