name: Terraform
on:
  push:
    branches:
        - master
    paths:
        - '**.tf'
        - '**.tfvars'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform/infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: 1.7

      - name: Terraform init
        run: terraform init
        env:
           TF_VAR_aws_region: eu-west-3

      - name: Terraform format
        run: terraform fmt --check -recursive
        continue-on-error: true

      - name: Terraform validation
        run: terraform validate
        continue-on-error: true
 
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@master
        env:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: TFLint
        uses: terraform-linters/setup-tflint@v3
      - run: tflint --recursive
        continue-on-error: true

      - name: TFsec
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true

      - name: Checkov
        uses: bridgecrewio/checkov-action@v3
        continue-on-error: true